### ISSUE TITLE
Popup boxes not closing in Chrome

### ISSUE THREAD

**Issue by wdahdul** [phenoscape/phenoscape-kb-web-ui#17]
Term info popup box stays open and doesn't disappear after other terms are clicked. 

<img width="813" alt="screen shot 2018-09-05 at 11 22 13 am" src="https://user-images.githubusercontent.com/957012/45113020-1547aa00-b0fe-11e8-944d-71e8ca15e813.png">

**Comment by wdahdul** [comment]
This also happens in Firefox.

**Comment by wdahdul** [comment]
Still an issue in Chrome and Firefox.

**Comment by balhoff** [comment]
Should be fixed by #74.
