### ISSUE TITLE
Allow query on exact search term and not returning subtypes 

### ISSUE THREAD

**Issue by wdahdul** [phenoscape/phenoscape-kb-web-ui#22]
For example, query 'Cyprinidae' and not return children, only annotations directly to Cyprinidae
Also, query 'dorsal fin'  and not return 'anterior dorsal fin', only return annotations directly to dorsal fin.

**Comment by hlapp** [comment]
@wdahdul Do we need to have this done for the SSB workshop? It was originally in the list for the Evolution 2019 workshop, but (obviously) wasn't completed.

**Comment by wdahdul** [comment]
Closing this because we can filter in RPhenoscape, and that should address the issue with needing to remove subtypes from results. (From discussion with Paula today).
