### ISSUE TITLE
Misaligned sample query boxes in homepage

### ISSUE THREAD

**Issue by wdahdul** [phenoscape/phenoscape-kb-web-ui#29]
The six query boxes appear misaligned in Chrome (see attached). In Safari, the misalignment happens when resizing the browser window.

<img width="1262" alt="screen shot 2018-11-15 at 10 52 40 am" src="https://user-images.githubusercontent.com/957012/48575078-d84e1f80-e8c5-11e8-80ef-2a8a9d213959.png">

**Comment by balhoff** [comment]
Fixed with new layout.
