### ISSUE TITLE
download data error

### ISSUE THREAD

**Issue by wdahdul** [phenoscape/phenoscape-kb-web-ui#40]
download data error in beta KB for the query:
entity: fin, 
taxon: Ictaluridae
include: parts

502 proxy error
Proxy Error

The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request GET /api/taxon/annotations.

Reason: Error reading from remote server

Apache/2.4.7 (Ubuntu) Server at kb.phenoscape.org Port 443

**Comment by wdahdul** [comment]
Only the taxon annotations tab gives this error. The downloads for the other tabs work fine!

**Comment by balhoff** [comment]
This was a problem with the startup script of the web service application.
