### ISSUE TITLE
presence phenotype shown duplicated 

### ISSUE THREAD

**Issue by wdahdul** [phenoscape/phenoscape-kb-web-ui#53]
The annotation in the Phenex file for is 'pelvic fin' 'present' (coded for Ameiurus nebulosus). KB shows two phenotypes, one correct (pelvic fin present) and one just to 'pelvic fin' without quality. 

<img width="823" alt="Screen Shot 2020-01-05 at 10 13 40 PM" src="https://user-images.githubusercontent.com/957012/71793001-ecdd0200-3008-11ea-8e9d-6557329fed36.png">

**Comment by balhoff** [comment]
Should be fixed by next KB load.
