### ISSUE TITLE
Di Dario 2004 file not loading in KB

### ISSUE THREAD

**Issue by wdahdul** [phenoscape/phenoscape-kb-web-ui#55]
The label appears in the dropdown menu but data table doesn't update with phenotypes. Using safari.

**Comment by balhoff** [comment]
This is likely related to a problematic URI for this paper (I fixed). Here are all the publication IRIs; we should improve the ones that link to Google: http://yasgui.org/short/-0Q3wxkxv

**Comment by wdahdul** [comment]
Jim updated the Publication DOI/URI. Check on this when KB is rebuilt

**Comment by wdahdul** [comment]
I updated many files that had reference links to google, but for some references, there were no better links available: https://docs.google.com/spreadsheets/d/1-absvhC2AH8kQwU4UU37YqKuzhFWVxUfR0Q72Ds8R6g/edit#gid=0

**Comment by wdahdul** [comment]
This paper now appears in the KB correctly with the new KB build.
