### ISSUE TITLE
Missing taxon VTO:0084440 in KB

### ISSUE THREAD

**Issue by wdahdul** [phenoscape/phenoscape-kb-web-ui#58]
The VTO term "Paedocypris sp. (Britz and Conway 2009)" doesn't appear in KB although the identifier is valid in ontobee: http://purl.obolibrary.org/obo/VTO_0084440, and there are annotations to the taxon in the Phenex file (Britz and Conway 2009). The other taxa from this matrix do appear in the KB, just seems that this one in particular is missing.

**Comment by wdahdul** [comment]
also couldn't find it using rphenoscape:
```
> pk_taxon_detail("Paedocypris sp. (Britz and Conway 2009)")
Warning message:
Could not find "Paedocypris sp. (Britz and Conway 2009)" in the database. Please check your input. 
```

**Comment by balhoff** [comment]
This looks like it will be in the next KB load—it was added to the file last month (https://github.com/phenoscape/phenoscape-data/commit/7deab33677d5273c58253c86f90b0a2932c219ea#diff-8735dd4d3c7a0e6e89de39b91895ec5f).
